export const ANALYTICS_EVENTS = {
  MEAL_UPLOADED: 'meal_uploaded',
  MEAL_RATED: 'meal_rated',
  RECIPE_REQUESTED: 'recipe_requested',
  RECIPE_UNREQUESTED: 'recipe_unrequested',
  RECIPE_UNLOCKED: 'recipe_unlocked',
  RECIPE_ADDED: 'recipe_added',
  SCORECARD_SHARED: 'scorecard_shared',
  FEED_SCROLLED: 'feed_scrolled',
  MAP_PIN_TAPPED: 'map_pin_tapped',
  AUTH_COMPLETED: 'auth_completed',
  STREAK_MILESTONE: 'streak_milestone',
  RESTAURANT_SUBSCRIBED: 'restaurant_subscribed',
  RESTAURANT_REVEALED: 'restaurant_revealed',
  MEAL_DELETED: 'meal_deleted',
  PROFILE_VIEWED: 'profile_viewed',
  PROFILE_FOLLOW: 'profile_follow',
  PROFILE_UNFOLLOW: 'profile_unfollow',
  PROFILE_EDIT_SAVED: 'profile_edit_saved',
  PROFILE_PRIVACY_CHANGED: 'profile_privacy_changed',
  PROFILE_MEAL_GRID_TAPPED: 'profile_meal_grid_tapped',
  PROFILE_FOLLOWERS_VIEWED: 'profile_followers_viewed',
  PROFILE_FOLLOWING_VIEWED: 'profile_following_viewed',
  PROFILE_USER_REPORTED: 'profile_user_reported',
  PROFILE_USER_BLOCKED: 'profile_user_blocked',
  FEED_TAB_SWITCHED: 'feed_tab_switched',
  FOLLOWING_FEED_VIEWED: 'following_feed_viewed',
  DISCOVER_FEED_VIEWED: 'discover_feed_viewed',
  FOLLOWING_FEED_EMPTY: 'following_feed_empty',
  FOLLOW_SUGGESTION_SHOWN: 'follow_suggestion_shown',
  FOLLOW_SUGGESTION_TAPPED: 'follow_suggestion_tapped',
  FOLLOW_PROMPT_AFTER_RATING: 'follow_prompt_after_rating',
  NEW_MEALS_PILL_SHOWN: 'new_meals_pill_shown',
  NEW_MEALS_PILL_TAPPED: 'new_meals_pill_tapped',

  // Tiers & private posts
  PLAN_UPGRADE_STARTED: 'plan_upgrade_started',
  PLAN_UPGRADE_COMPLETED: 'plan_upgrade_completed',
  PLAN_DOWNGRADED: 'plan_downgraded',
  PRIVATE_FEED_INVITE_SENT: 'private_feed_invite_sent',
  PRIVATE_FEED_INVITE_ACCEPTED: 'private_feed_invite_accepted',
  PRIVATE_FEED_INVITE_DECLINED: 'private_feed_invite_declined',
  PRIVATE_FEED_MEMBER_LEFT: 'private_feed_member_left',
  PRIVATE_MEAL_RATED: 'private_meal_rated',
  MULTI_PHOTO_UPSELL_SHOWN: 'multi_photo_upsell_shown',
  MULTI_PHOTO_UPSELL_TAPPED: 'multi_photo_upsell_tapped',
} as const;
